
env:
    
    - GO111MODULE=on
    - CGO_ENABLED=0
before:
    hooks: 
        - go mod tidy
        - go mod download

builds:
    - env:
          - CGO_ENABLED=0
      
      main: ./cmd/todo/main.go
      binary: main

archives:
    
    - format: tar.gz
     
      format_overrides:
          - goos: windows
            format: zip
      
      name_template: '{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}'
      
      replacements:
          amd64: 64bit
          386: 32bit
          arm: ARM
          arm64: ARM64
          darwin: macOS
          linux: Linux
          windows: Windows
      files:
          - Readme.MD

checksum:
    name_template: 'checksums.txt'

snapshot:
    name_template: '{{ .Tag }}-next'
changelog:
    sort: asc
    filters:
        exclude:
            - '^docs:'
            - '^test:'
            - 'README'
            - Merge pull request
            - Merge branch

brews:
    - github:
          owner: nitinmewar
          name: homebrew-todo-cli
      folder: Formula
      homepage: https://github.com/nitinmewar/todo-cli
      description: cli apps for productiity